apiVersion: v1
kind: Service
metadata:
  name: dispatch-app-service
spec:
  # type: NodePort
  selector:
    app: DispatchApp
  ports:
    - protocol: TCP
      port: 9279
      targetPort: 8000
      # nodePort: 30010