apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world-rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 250Mi
    limits:
      cpu: 800m
      memory: 500Mi