apiVersion: v1
kind: Service
metadata:
  name: ordering-app-service
spec:
  # type: NodePort
  selector:
    app: OrderingApp
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 80
      # nodePort: 30008