apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-app-deployment
spec:
  selector:
    matchLabels:
      app: OrderingApp
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: OrderingApp
    spec:
      containers:
      - name: ordering-image
        image: ordering
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80